// Auth/Account Actions
export const ACCOUNT_FORM_UPDATE = 'ACCOUNT_FORM_UPDATE';

export const ACCOUNT_SIGNUP_REQUEST = 'ACCOUNT_SIGNUP_REQUEST';
export const ACCOUNT_SIGNUP_SUCCESS = 'ACCOUNT_SIGNUP_SUCCESS';
export const ACCOUNT_SIGNUP_FAILUE = 'ACCOUNT_SIGNUP_FAILUE';

export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAILUE = 'ACCOUNT_LOGIN_FAILUE';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

export const FETCH_ACCOUNT_BY_ID_REQUEST = 'FETCH_ACCOUNT_BY_ID_REQUEST';
export const FETCH_ACCOUNT_BY_ID_SUCCESS = 'FETCH_ACCOUNT_BY_ID_SUCCESS';
export const FETCH_ACCOUNT_BY_ID_FAILUE = 'FETCH_ACCOUNT_BY_ID_FAILUE';
export const PROFILE_FORM_UPDATE = 'PROFILE_FORM_UPDATE';



// Product Actions
export const FETCH_ALL_PRODUCTS_REQUEST = 'FETCH_ALL_PRODUCTS_REQUEST';
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_FAILURE = 'FETCH_ALL_PRODUCTS_FAILURE';

export const FETCH_PRODUCT_BY_ID_REQUEST = 'FETCH_PRODUCT_BY_ID_REQUEST';
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_FAILURE = 'FETCH_PRODUCT_BY_ID_FAILURE';

export const FETCH_PRODUCT_BY_CATEGORY_REQUEST = 'FETCH_PRODUCT_BY_CATEGORY_REQUEST';
export const FETCH_PRODUCT_BY_CATEGORY_SUCCESS = 'FETCH_PRODUCT_BY_CATEGORY_SUCCESS';
export const FETCH_PRODUCT_BY_CATEGORY_FAILURE = 'FETCH_PRODUCT_BY_CATEGORY_FAILURE';

export const FETCH_PRODUCTS_BY_ACCOUNT_REQUEST = 'FETCH_PRODUCTS_BY_ACCOUNT_REQUEST';
export const FETCH_PRODUCTS_BY_ACCOUNT_SUCCESS = 'FETCH_PRODUCTS_BY_ACCOUNT_SUCCESS';
export const FETCH_PRODUCTS_BY_ACCOUNT_FAILURE = 'FETCH_PRODUCTS_BY_ACCOUNT_FAILURE';

export const ADD_NEW_PRODUCT_IMAGE = 'ADD_NEW_PRODUCT_IMAGE';

export const FETCH_S3_SIGNED_REQUEST = 'FETCH_S3_SIGNED_REQUEST';
export const FETCH_S3_SIGNED_SUCCESS = 'FETCH_S3_SIGNED_SUCCESS';
export const FETCH_S3_SIGNED_FAILURE = 'FETCH_S3_SIGNED_FAILURE';

export const PRODUCT_FORM_UPDATE = 'PRODUCT_FORM_UPDATE';

export const CREATE_NEW_PRODUCT_REQUEST = 'CREATE_NEW_PRODUCT_REQUEST';
export const CREATE_NEW_PRODUCT_SUCCESS = 'CREATE_NEW_PRODUCT_SUCCESS';
export const CREATE_NEW_PRODUCT_FAILURE = 'CREATE_NEW_PRODUCT_FAILURE';

// Checkout Actions
export const CREATE_PAYMENT_REQUEST = 'CREATE_PAYMENT_REQUEST';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_FAILURE = 'CREATE_PAYMENT_FAILURE';
