export const ACCOUNT_FORM_UPDATE = 'ACCOUNT_FORM_UPDATE';

export const ACCOUNT_SIGNUP_REQUEST = 'ACCOUNT_SIGNUP_REQUEST';
export const ACCOUNT_SIGNUP_SUCCESS = 'ACCOUNT_SIGNUP_SUCCESS';
export const ACCOUNT_SIGNUP_FAILUE = 'ACCOUNT_SIGNUP_FAILUE';

export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAILUE = 'ACCOUNT_LOGIN_FAILUE';

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
